### ISSUE TITLE
Not all URLs in the topic of a channel are clickable 

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Vision#1]
For some reason not all URLs in the topic of a channel are clickable.   

The clickable URLs seem to be displayed with a proportional font, the non-clickable are fixed-width.

**Comment by bbjimmy** [comment]
The clickable urls start with http://  the ones that are not clickable start with https://

**Comment by humdingerb** [comment]
Nope, https://gist.github.com  for example is clickable in another channel.
