### ISSUE TITLE
Vision fails to build on 64 bit

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Vision#12]
hrev50589 x86_64
I tried to build both both 0.9.7r949 and 0.9.8; both failed
Build logs are attached

**Comment by Vidrep** [comment]
[Vision0.9.7r949_build_log.txt](https://github.com/HaikuArchives/Vision/files/523080/Vision0.9.7r949_build_log.txt)
[Vision0.9.8_build_log.txt](https://github.com/HaikuArchives/Vision/files/523081/Vision0.9.8_build_log.txt)

**Comment by waddlesplash** [comment]
Fixed. (Use the makefile now, instead of the jamfile.)

**Comment by Vidrep** [comment]
The issue is that Vision will not build on 64 bit using the haikuporter recipes (both attached)
