### ISSUE TITLE
Vision broken on x86 builds

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Vision#18]
x86 and x86h builds are broken.
Desktop Error message:
Could not open "Vision" (Missing symbol: _ZN7BStringixEl).

From the syslog:
KERN: runtime_loader: /boot/system/apps/Vision/Vision: Could not resolve symbol '_ZN7BStringixEl'
KERN: runtime_loader: /boot/system/apps/Vision/Vision: Troubles relocating: Symbol not found

Launching from terminal:
runtime_loader: /boot/system/apps/Vision/Vision: Could not resolve symbol '_ZN7BStringixEl'
resolve symbol "_ZN7BStringixEl" returned: -2147478780
runtime_loader: /boot/system/apps/Vision/Vision: Troubles relocating: Symbol not found

**Comment by Vidrep** [comment]
Building and installing Vision 0.9.8 resolves the issue on x86_gcc5h.

**Comment by humdingerb** [comment]
Thanks.
