### ISSUE TITLE
Clean up strings and usages of B_TRANSLATE

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/Vision#19]
There's a lot of questionable wording and non-conformance to the HIG (e.g. Title Casing instead of sentence casing) as well as a LOT of string-building with interim B_TRANSLATE calls that should be replaced either by SetToFormat() or .ReplaceFirst() or even BMessageFormat. These should all get cleaned up before actually sending the catkeys to translators.

@humdingerb: I've done the annoying and tedious work of getting Vision onto the locale kit, do you have time / are interested in doing this part? You probably know how to do it better than I. 😃

**Comment by waddlesplash** [comment]
The code also doesn't really conform to Haiku coding style in a number of ways (no 80-char limit, incorrect line wrapping, etc.) so please do clean up as you go along (or not, I don't care if you leave it as is, but might make your job easier to reformat, too.)

**Comment by humdingerb** [comment]
I can work on that. But does Vision use layout managemant throughout? Without it, there isn't much sense in localization, right?
I have tried in the past to fix certain layout problems (cut off strings in menus etc.), but had to give up...

**Comment by waddlesplash** [comment]
Fixed in 1fca397f531b3acfe859039aae411a1c1725c430.
