### ISSUE TITLE
Connection thread names should be better named

### ISSUE THREAD

**Issue by NattyNarwhal** [HaikuArchives/Vision#21]
Vision.cpp#L1402 is the offending function. The names are somewhat silly at best to possibly offensive at worst. Still, it's not clear that these are connection threads, and they could be better named, even something as simple as "Connection thread 32." If the silly stuff can be kept, it may be worth just removing the questionable ones and clarifying that these are connection threads.

IRC log in #haiku:

> 22:32 < Vidrep> Just now I couldn't quit Vision
> 
> 22:33 < Vidrep> Attached the debugger and got some weird thread like "thread 451: s>geisha_slut_villainess" and "thread 446: the_spirits_within"
> 
> 22:34 < Duggan> "like"?
> 
> 22:34 < Vidrep> :) Not like. It was that
> 
> 22:34 < Vidrep> Try to reboot again...
> 
> 22:35 -!- Vidrep [~vision@d108-173-61-127.abhsia.telus.net] has quit [Client Quit]
> 
> 22:41 < Duggan> Vision.cpp line 1329... list of thread names.... they look like they should probably be changed...

**Comment by humdingerb** [comment]
Please don't go overboard with "purifying" everything. I can understand that "geisha_slut_villainess" without the context it was jokingly put in there is above the threshold for many. But please don't censor every harmless word a puritan may take offense with, like "naked", "nipple" or "buttocks". The About messages from the original authors have already been cleaned of this filthy filthy word "nipple" and the allusion to the nerd affection for Ms. Portman.

Thread names are quite hidden and obscure. Please don't remove the little of nerdy fun still left that was a hallmark of BeOS.

**Comment by anevilyak** [comment]
Seconded, I really don't see the point in trying to censor everything like this, especially when most of the "questionable" ones are actually references to things like webcomics and onion articles that were popular in the days when the code was originally written.

**Comment by waddlesplash** [comment]
Makes sense to me, I suppose. Closing as wontfix.
