### ISSUE TITLE
After updating to hrev51457 Vision error

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Vision#24]
Could not open "Vision" (Missing symbol: DrawScrollViewFrame_Q28BPrivate12BControlLookP5BViewR5BRectG5BRectT4RC9rgb_color12border_styleUIUI).

**Comment by mmuman** [comment]
There has been some change on BControlLook recently, the package likely has to be rebuilt.

**Comment by humdingerb** [comment]
Yes. That would be a haikuports issue, but I don't think we need a ticket for that there either, because it's known.
