### ISSUE TITLE
Vision crashes when resize internal chat frame

### ISSUE THREAD

**Issue by unspacyar** [HaikuArchives/Vision#32]
When try to resize the chat frame, moving the bar that is between the chat and contact list, Vision crashes.

I attach the report.

Tested in Haiku x86_gcc2

**Comment by unspacyar** [comment]
Here is the report:
<details>
Debug information for team /boot/system/apps/Vision/Vision (15676):
CPU(s): 2x Intel Pentium
Memory: 1.93 GiB total, 691.79 MiB used
Haiku revision: hrev52092 Jul 10 2018 23:07:58 (BePC)

Active Threads:
	thread 15676: Vision (main)
	thread 15679: the_spirits_within 
	thread 15681: w>Setup window 
	thread 15689: l>will_code_for_food 
	thread 15690: t>Kenichi 
	thread 15691: s>magic 8-nipple 
	thread 15698: team 15676 debug task 
	thread 15688: w>#haiku-es - Vision 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x72189aa0	0x1c0cc7a	WindowListItem::pAgent(WindowListItem) + 0x6 
			Disassembly:
				WindowListItem::pAgent(WindowListItem):
				0x01c0cc74:               55  push %ebp
				0x01c0cc75:             89e5  mov %esp, %ebp
				0x01c0cc77:           8b4508  mov 0x8(%ebp), %eax
				0x01c0cc7a:           8b4034  mov 0x34(%eax), %eax <--

			Frame memory:
				[0x72189a98]  ...r....   88 9b 18 72 f5 e5 b9 01
		0x72189b90	0x1b9e5f0	ClientWindow::MessageReceived(BMessage*) + 0x7f0 
		0x72189bc0	0xf50661	BLooper::DispatchMessage(BMessage*, BHandler*) + 0x59 
		0x72189da0	0x103a48c	BWindow::DispatchMessage(BMessage*, BHandler*) + 0x182c 
		0x72189e00	0x103eb06	BWindow::task_looper() + 0x28e 
		0x72189e30	0xf51b09	BLooper::_task0_(void*) + 0x3d 
		0x72189e58	0x4b2b1d	thread_entry + 0x21 
		00000000	0x60eb2250	commpage_thread_exit + 0 

		Registers:
			  eip:	0x01c0cc7a
			  esp:	0x72189a98
			  ebp:	0x72189a98
			  eax:	0x00000000
			  ebx:	0x01c3fae0
			  ecx:	0x182f39c4
			  edx:	0x00000000
			  esi:	0x182f7f00
			  edi:	0x182f7f00
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	nan
			  st1:	0
			  st2:	0.9
			  st3:	27
			  st4:	1
			  st5:	2
			  st6:	897
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0x6600, 0xe666}
			  mm3:	{0, 0, 0, 0xd800}
			  mm4:	{0, 0, 0, 0x8000}
			  mm5:	{0, 0, 0, 0x8000}
			  mm6:	{0, 0, 0, 0xe040}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0x4e98, 0x79fe, 0, 0, 0x8086, 0x2919, 0x103c, 0x360b}
			 xmm1:	{0x4e98, 0x79fe, 0, 0, 0x8086, 0x2919, 0x103c, 0x360b}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0x6aea, 0x1bf0, 0x5bec, 0x4a8d, 0x7695, 0x9b74, 0x5609, 0x302d}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	2753	0x00307000	0x00331000	0x00331000	0x0033c000	lib    	/boot/system/lib/libIex-2_2.so.23.0.0
	2740	0x0034f000	0x0035b000	0x0035b000	0x0035e000	add-on 	/boot/system/add-ons/Translators/PNGTranslator
	2714	0x00480000	0x00556000	0x00556000	0x005a2000	lib    	/boot/system/lib/libroot.so
	2731	0x005af000	0x005bb000	0x005bb000	0x005be000	add-on 	/boot/system/add-ons/Translators/TIFFTranslator
	2728	0x005c8000	0x005d8000	0x005d8000	0x005db000	add-on 	/boot/system/add-ons/Translators/WonderBrushTranslator
	2737	0x005e1000	0x00602000	0x00602000	0x00608000	add-on 	/boot/system/add-ons/Translators/RAWTranslator
	2747	0x0060f000	0x0061e000	0x0061e000	0x0061f000	lib    	/boot/system/lib/libicns.so.1.2.0
	2709	0x0064d000	0x00744000	0x00744000	0x00747000	lib    	/boot/system/lib/libtextencoding.so
	2730	0x00753000	0x007a3000	0x007a3000	0x007af000	lib    	/boot/system/lib/libwebp.so.7.0.2
	2729	0x007d1000	0x007dd000	0x007dd000	0x007e0000	add-on 	/boot/system/add-ons/Translators/WebPTranslator
	2733	0x00831000	0x0086d000	0x0086d000	0x00872000	lib    	/boot/system/lib/libjpeg.so.9.3.0
	2748	0x008cc000	0x008d8000	0x008d8000	0x008db000	add-on 	/boot/system/add-ons/Translators/ICOTranslator
	2705	0x00910000	0x0092f000	0x0092f000	0x00932000	lib    	/boot/system/runtime_loader
	2743	0x00940000	0x00950000	0x00950000	0x00954000	add-on 	/boot/system/add-ons/Translators/JPEG2000Translator
	2725	0x00990000	0x009e7000	0x009e7000	0x00a0b000	lib    	/boot/system/lib/libssl.so.1.0.0
	2761	0x00a26000	0x00a2b000	0x00a2b000	0x00a2d000	add-on 	/boot/system/add-ons/Translators/IFF_ILBMTranslator
	2711	0x00a48000	0x00a7d000	0x00a7d000	0x00a85000	lib    	/boot/system/lib/libnetwork.so
	2710	0x00aa5000	0x00c53000	0x00c53000	0x00cb3000	lib    	/boot/system/lib/libtracker.so
	2758	0x00cb3000	0x00d10000	0x00d10000	0x00d23000	lib    	/boot/system/lib/libIlmImfUtil-2_2.so.23.0.0
	2722	0x00d2a000	0x00d44000	0x00d44000	0x00d45000	lib    	/boot/system/lib/libz.so.1.2.11
	2745	0x00d47000	0x00d5b000	0x00d5b000	0x00d5f000	add-on 	/boot/system/add-ons/Translators/JPEGTranslator
	2760	0x00d64000	0x00d70000	0x00d70000	0x00d72000	add-on 	/boot/system/add-ons/Translators/STXTTranslator
	2713	0x00d76000	0x00da7000	0x00da7000	0x00db5000	lib    	/boot/system/lib/libstdc++.r4.so
	2707	0x00e3d000	0x0110e000	0x0110e000	0x011a8000	lib    	/boot/system/lib/libbe.so
	2734	0x011a8000	0x011b6000	0x011b6000	0x011b8000	add-on 	/boot/system/add-ons/Translators/TGATranslator
	2716	0x011b9000	0x0144a000	0x0144a000	0x014b3000	lib    	/boot/system/lib/libicui18n.so.57.1
	2712	0x014c0000	0x01523000	0x01523000	0x01537000	lib    	/boot/system/lib/libbnetapi.so
	2739	0x0153e000	0x01549000	0x01549000	0x0154c000	add-on 	/boot/system/add-ons/Translators/PPMTranslator
	2746	0x01552000	0x0155d000	0x0155d000	0x01560000	add-on 	/boot/system/add-ons/Translators/ICNSTranslator
	2755	0x01562000	0x0156d000	0x0156d000	0x01571000	lib    	/boot/system/lib/libIlmThread-2_2.so.23.0.0
	2719	0x01575000	0x01580000	0x01580000	0x01583000	lib    	/boot/system/lib/libiculx.so.57.1
	2732	0x01583000	0x015ea000	0x015ea000	0x015f4000	lib    	/boot/system/lib/libtiff.so.5.3.0
	2720	0x015fe000	0x01637000	0x01637000	0x0166e000	lib    	/boot/system/lib/libicutu.so.57.1
	2741	0x01674000	0x0169e000	0x0169e000	0x016a4000	lib    	/boot/system/lib/libpng16.so.16.34.0
	2735	0x016a5000	0x016b2000	0x016b2000	0x016b5000	add-on 	/boot/system/add-ons/Translators/SGITranslator
	2718	0x016b8000	0x0170b000	0x0170b000	0x01716000	lib    	/boot/system/lib/libicule.so.57.1
	2750	0x01747000	0x0175b000	0x0175b000	0x0175f000	add-on 	/boot/system/add-ons/Translators/GIFTranslator
	2708	0x01769000	0x01780000	0x01780000	0x01785000	lib    	/boot/system/lib/libtranslation.so
	2721	0x017f3000	0x01965000	0x01965000	0x01999000	lib    	/boot/system/lib/libicuuc.so.57.1
	2749	0x019b0000	0x019ba000	0x019ba000	0x019bc000	add-on 	/boot/system/add-ons/Translators/HVIFTranslator
	2744	0x019c1000	0x01a28000	0x01a28000	0x01a32000	lib    	/boot/system/lib/libjasper.so.4.0.0
	2752	0x01a42000	0x01a84000	0x01a84000	0x01a85000	lib    	/boot/system/lib/libHalf.so.23.0.0
	2742	0x01a8f000	0x01a99000	0x01a99000	0x01a9c000	add-on 	/boot/system/add-ons/Translators/PCXTranslator
	2717	0x01a9f000	0x01aa8000	0x01aa8000	0x01aaa000	lib    	/boot/system/lib/libicuio.so.57.1
	2759	0x01aae000	0x01aba000	0x01aba000	0x01abd000	add-on 	/boot/system/add-ons/Translators/BMPTranslator
	2756	0x01afd000	0x01b1c000	0x01b1c000	0x01b21000	lib    	/boot/system/lib/libImath-2_2.so.23.0.0
	2738	0x01b25000	0x01b34000	0x01b34000	0x01b37000	add-on 	/boot/system/add-ons/Translators/PSDTranslator
	2706	0x01b4a000	0x01c26000	0x01c26000	0x01c4a000	app    	/boot/system/apps/Vision/Vision
	2751	0x01c59000	0x01c65000	0x01c65000	0x01c67000	add-on 	/boot/system/add-ons/Translators/EXRTranslator
	2724	0x01c71000	0x01dd4000	0x01dd4000	0x01e7c000	lib    	/boot/system/lib/libcrypto.so.1.0.0
	2762	0x01eb6000	0x01ec6000	0x01ec6000	0x01eca000	lib    	/boot/system/lib/libroot-addon-icu.so
	2754	0x01ee7000	0x01eed000	0x01eed000	0x01eef000	lib    	/boot/system/lib/libIexMath-2_2.so.23.0.0
	2736	0x01f1f000	0x01f30000	0x01f30000	0x01f34000	add-on 	/boot/system/add-ons/Translators/RTFTranslator
	2723	0x01f45000	0x01f49000	0x01f49000	0x01f4a000	lib    	/boot/system/lib/libbsd.so
	2757	0x01f84000	0x0223d000	0x0223d000	0x0240a000	lib    	/boot/system/lib/libIlmImf-2_2.so.23.0.0
	2715	0x02437000	0x03cb5000	0x03cb5000	0x03cb6000	lib    	/boot/system/lib/libicudata.so.57.1
	2704	0x60eb2000	0x60eba000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	39796	0x00113000	0x00123000	        64	rw-        	full          	rld heap
	39795	0x00145000	0x00155000	        64	rw-        	full          	rld heap
	39794	0x0016e000	0x00176000	        32	rw-        	full          	rld heap
	39742	0x00191000	0x00192000	         4	rw-S       	full          	_rld_debug_
	39741	0x002ce000	0x002de000	        64	rw-        	full          	rld heap
	39865	0x00307000	0x00331000	       168	r-x        	full          	libIex-2_2.so.23.0.0_seg0ro
	39866	0x00331000	0x0033b000	        40	rw-        	full          	libIex-2_2.so.23.0.0_seg1rw
	39867	0x0033b000	0x0033c000	         4	rw-        	full          	libIex-2_2.so.23.0.0_seg2rw
	39838	0x0034f000	0x0035b000	        48	r-x        	full          	PNGTranslator_seg0ro
	39839	0x0035b000	0x0035e000	        12	rw-        	full          	PNGTranslator_seg1rw
	39765	0x00480000	0x00556000	       856	r-x        	full          	libroot.so_seg0ro
	39766	0x00556000	0x0056a000	        80	rw-        	full          	libroot.so_seg1rw
	39767	0x0056a000	0x005a2000	       224	rw-        	full          	libroot.so_seg2rw
	39820	0x005af000	0x005bb000	        48	r-x        	full          	TIFFTranslator_seg0ro
	39821	0x005bb000	0x005be000	        12	rw-        	full          	TIFFTranslator_seg1rw
	39813	0x005c8000	0x005d8000	        64	r-x        	full          	WonderBrushTranslator_seg0ro
	39814	0x005d8000	0x005db000	        12	rw-        	full          	WonderBrushTranslator_seg1rw
	39832	0x005e1000	0x00602000	       132	r-x        	full          	RAWTranslator_seg0ro
	39833	0x00602000	0x00608000	        24	rw-        	full          	RAWTranslator_seg1rw
	39853	0x0060f000	0x0061e000	        60	r-x        	full          	libicns.so.1.2.0_seg0ro
	39854	0x0061e000	0x0061f000	         4	rw-        	full          	libicns.so.1.2.0_seg1rw
	39751	0x0064d000	0x00744000	       988	r-x        	full          	libtextencoding.so_seg0ro
	39752	0x00744000	0x00746000	         8	rw-        	full          	libtextencoding.so_seg1rw
	39753	0x00746000	0x00747000	         4	rw-        	full          	libtextencoding.so_seg2rw
	39817	0x00753000	0x007a3000	       320	r-x        	full          	libwebp.so.7.0.2_seg0ro
	39818	0x007a3000	0x007ad000	        40	rw-        	full          	libwebp.so.7.0.2_seg1rw
	39819	0x007ad000	0x007af000	         8	rw-        	full          	libwebp.so.7.0.2_seg2rw
	39815	0x007d1000	0x007dd000	        48	r-x        	full          	WebPTranslator_seg0ro
	39816	0x007dd000	0x007e0000	        12	rw-        	full          	WebPTranslator_seg1rw
	39824	0x00831000	0x0086d000	       240	r-x        	full          	libjpeg.so.9.3.0_seg0ro
	39825	0x0086d000	0x00872000	        20	rw-        	full          	libjpeg.so.9.3.0_seg1rw
	39855	0x008cc000	0x008d8000	        48	r-x        	full          	ICOTranslator_seg0ro
	39856	0x008d8000	0x008db000	        12	rw-        	full          	ICOTranslator_seg1rw
	39738	0x00910000	0x0092f000	       124	r-x        	full          	runtime_loader_seg0ro
	39739	0x0092f000	0x00931000	         8	rw-        	full          	runtime_loader_seg1rw
	39740	0x00931000	0x00932000	         4	rw-        	full          	runtime_loader_bss1
	39844	0x00940000	0x00950000	        64	r-x        	full          	JPEG2000Translator_seg0ro
	39845	0x00950000	0x00954000	        16	rw-        	full          	JPEG2000Translator_seg1rw
	39792	0x00990000	0x009e7000	       348	r-x        	full          	libssl.so.1.0.0_seg0ro
	39793	0x009e7000	0x00a0b000	       144	rw-        	full          	libssl.so.1.0.0_seg1rw
	39883	0x00a26000	0x00a2b000	        20	r-x        	full          	IFF_ILBMTranslator_seg0ro
	39884	0x00a2b000	0x00a2d000	         8	rw-        	full          	IFF_ILBMTranslator_seg1rw
	39757	0x00a48000	0x00a7d000	       212	r-x        	full          	libnetwork.so_seg0ro
	39758	0x00a7d000	0x00a80000	        12	rw-        	full          	libnetwork.so_seg1rw
	39759	0x00a80000	0x00a85000	        20	rw-        	full          	libnetwork.so_seg2rw
	39754	0x00aa5000	0x00c53000	      1720	r-x        	full          	libtracker.so_seg0ro
	39755	0x00c53000	0x00cb1000	       376	rw-        	full          	libtracker.so_seg1rw
	39756	0x00cb1000	0x00cb3000	         8	rw-        	full          	libtracker.so_seg2rw
	39877	0x00cb3000	0x00d10000	       372	r-x        	full          	libIlmImfUtil-2_2.so.23.0.0_seg
	39878	0x00d10000	0x00d23000	        76	rw-        	full          	libIlmImfUtil-2_2.so.23.0.0_seg
	39785	0x00d2a000	0x00d44000	       104	r-x        	full          	libz.so.1.2.11_seg0ro
	39786	0x00d44000	0x00d45000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	39849	0x00d47000	0x00d5b000	        80	r-x        	full          	JPEGTranslator_seg0ro
	39850	0x00d5b000	0x00d5f000	        16	rw-        	full          	JPEGTranslator_seg1rw
	39881	0x00d64000	0x00d70000	        48	r-x        	full          	STXTTranslator_seg0ro
	39882	0x00d70000	0x00d72000	         8	rw-        	full          	STXTTranslator_seg1rw
	39762	0x00d76000	0x00da7000	       196	r-x        	full          	libstdc++.r4.so_seg0ro
	39763	0x00da7000	0x00db2000	        44	rw-        	full          	libstdc++.r4.so_seg1rw
	39764	0x00db2000	0x00db5000	        12	rw-        	full          	libstdc++.r4.so_seg2rw
	39746	0x00e3d000	0x0110e000	      2884	r-x        	full          	libbe.so_seg0ro
	39747	0x0110e000	0x011a6000	       608	rw-        	full          	libbe.so_seg1rw
	39748	0x011a6000	0x011a8000	         8	rw-        	full          	libbe.so_seg2rw
	39826	0x011a8000	0x011b6000	        56	r-x        	full          	TGATranslator_seg0ro
	39827	0x011b6000	0x011b8000	         8	rw-        	full          	TGATranslator_seg1rw
	39770	0x011b9000	0x0144a000	      2628	r-x        	full          	libicui18n.so.57.1_seg0ro
	39771	0x0144a000	0x014b2000	       416	rw-        	full          	libicui18n.so.57.1_seg1rw
	39772	0x014b2000	0x014b3000	         4	rw-        	full          	libicui18n.so.57.1_seg2rw
	39760	0x014c0000	0x01523000	       396	r-x        	full          	libbnetapi.so_seg0ro
	39761	0x01523000	0x01537000	        80	rw-        	full          	libbnetapi.so_seg1rw
	39836	0x0153e000	0x01549000	        44	r-x        	full          	PPMTranslator_seg0ro
	39837	0x01549000	0x0154c000	        12	rw-        	full          	PPMTranslator_seg1rw
	39851	0x01552000	0x0155d000	        44	r-x        	full          	ICNSTranslator_seg0ro
	39852	0x0155d000	0x01560000	        12	rw-        	full          	ICNSTranslator_seg1rw
	39870	0x01562000	0x0156d000	        44	r-x        	full          	libIlmThread-2_2.so.23.0.0_seg0
	39871	0x0156d000	0x01571000	        16	rw-        	full          	libIlmThread-2_2.so.23.0.0_seg1
	39777	0x01575000	0x01580000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	39778	0x01580000	0x01583000	        12	rw-        	full          	libiculx.so.57.1_seg1rw
	39822	0x01583000	0x015ea000	       412	r-x        	full          	libtiff.so.5.3.0_seg0ro
	39823	0x015ea000	0x015f4000	        40	rw-        	full          	libtiff.so.5.3.0_seg1rw
	39779	0x015fe000	0x01637000	       228	r-x        	full          	libicutu.so.57.1_seg0ro
	39780	0x01637000	0x0163c000	        20	rw-        	full          	libicutu.so.57.1_seg1rw
	39781	0x0163c000	0x0166e000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	39840	0x01674000	0x0169e000	       168	r-x        	full          	libpng16.so.16.34.0_seg0ro
	39841	0x0169e000	0x016a4000	        24	rw-        	full          	libpng16.so.16.34.0_seg1rw
	39828	0x016a5000	0x016b2000	        52	r-x        	full          	SGITranslator_seg0ro
	39829	0x016b2000	0x016b5000	        12	rw-        	full          	SGITranslator_seg1rw
	39775	0x016b8000	0x0170b000	       332	r-x        	full          	libicule.so.57.1_seg0ro
	39776	0x0170b000	0x01716000	        44	rw-        	full          	libicule.so.57.1_seg1rw
	39859	0x01747000	0x0175b000	        80	r-x        	full          	GIFTranslator_seg0ro
	39860	0x0175b000	0x0175f000	        16	rw-        	full          	GIFTranslator_seg1rw
	39749	0x01769000	0x01780000	        92	r-x        	full          	libtranslation.so_seg0ro
	39750	0x01780000	0x01785000	        20	rw-        	full          	libtranslation.so_seg1rw
	39782	0x017f3000	0x01965000	      1480	r-x        	full          	libicuuc.so.57.1_seg0ro
	39783	0x01965000	0x01998000	       204	rw-        	full          	libicuuc.so.57.1_seg1rw
	39784	0x01998000	0x01999000	         4	rw-        	full          	libicuuc.so.57.1_seg2rw
	39857	0x019b0000	0x019ba000	        40	r-x        	full          	HVIFTranslator_seg0ro
	39858	0x019ba000	0x019bc000	         8	rw-        	full          	HVIFTranslator_seg1rw
	39846	0x019c1000	0x01a28000	       412	r-x        	full          	libjasper.so.4.0.0_seg0ro
	39847	0x01a28000	0x01a2b000	        12	rw-        	full          	libjasper.so.4.0.0_seg1rw
	39848	0x01a2b000	0x01a32000	        28	rw-        	full          	libjasper.so.4.0.0_seg2rw
	39863	0x01a42000	0x01a84000	       264	r-x        	full          	libHalf.so.23.0.0_seg0ro
	39864	0x01a84000	0x01a85000	         4	rw-        	full          	libHalf.so.23.0.0_seg1rw
	39842	0x01a8f000	0x01a99000	        40	r-x        	full          	PCXTranslator_seg0ro
	39843	0x01a99000	0x01a9c000	        12	rw-        	full          	PCXTranslator_seg1rw
	39773	0x01a9f000	0x01aa8000	        36	r-x        	full          	libicuio.so.57.1_seg0ro
	39774	0x01aa8000	0x01aaa000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	39879	0x01aae000	0x01aba000	        48	r-x        	full          	BMPTranslator_seg0ro
	39880	0x01aba000	0x01abd000	        12	rw-        	full          	BMPTranslator_seg1rw
	39872	0x01afd000	0x01b1c000	       124	r-x        	full          	libImath-2_2.so.23.0.0_seg0ro
	39873	0x01b1c000	0x01b21000	        20	rw-        	full          	libImath-2_2.so.23.0.0_seg1rw
	39834	0x01b25000	0x01b34000	        60	r-x        	full          	PSDTranslator_seg0ro
	39835	0x01b34000	0x01b37000	        12	rw-        	full          	PSDTranslator_seg1rw
	39743	0x01b4a000	0x01c26000	       880	r-x        	full          	Vision_seg0ro
	39744	0x01c26000	0x01c49000	       140	rw-        	full          	Vision_seg1rw
	39745	0x01c49000	0x01c4a000	         4	rw-        	full          	Vision_seg2rw
	39861	0x01c59000	0x01c65000	        48	r-x        	full          	EXRTranslator_seg0ro
	39862	0x01c65000	0x01c67000	         8	rw-        	full          	EXRTranslator_seg1rw
	39789	0x01c71000	0x01dd4000	      1420	r-x        	full          	libcrypto.so.1.0.0_seg0ro
	39790	0x01dd4000	0x01e7a000	       664	rw-        	full          	libcrypto.so.1.0.0_seg1rw
	39791	0x01e7a000	0x01e7c000	         8	rw-        	full          	libcrypto.so.1.0.0_seg2rw
	39903	0x01eb6000	0x01ec6000	        64	r-x        	full          	libroot-addon-icu.so_seg0ro
	39904	0x01ec6000	0x01eca000	        16	rw-        	full          	libroot-addon-icu.so_seg1rw
	39868	0x01ee7000	0x01eed000	        24	r-x        	full          	libIexMath-2_2.so.23.0.0_seg0ro
	39869	0x01eed000	0x01eef000	         8	rw-        	full          	libIexMath-2_2.so.23.0.0_seg1rw
	39830	0x01f1f000	0x01f30000	        68	r-x        	full          	RTFTranslator_seg0ro
	39831	0x01f30000	0x01f34000	        16	rw-        	full          	RTFTranslator_seg1rw
	39787	0x01f45000	0x01f49000	        16	r-x        	full          	libbsd.so_seg0ro
	39788	0x01f49000	0x01f4a000	         4	rw-        	full          	libbsd.so_seg1rw
	39874	0x01f84000	0x0223d000	      2788	r-x        	full          	libIlmImf-2_2.so.23.0.0_seg0ro
	39875	0x0223d000	0x02409000	      1840	rw-        	full          	libIlmImf-2_2.so.23.0.0_seg1rw
	39876	0x02409000	0x0240a000	         4	rw-        	full          	libIlmImf-2_2.so.23.0.0_seg2rw
	39768	0x02437000	0x03cb5000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	39769	0x03cb5000	0x03cb6000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	39797	0x182d6000	0x18536000	      2432	rw-        	full          	heap
	39737	0x60eb2000	0x60eba000	        32	r-xSk      	full          	commpage
	39734	0x6108e000	0x61092000	        16	rw-        	full          	user area
	39806	0x6110e000	0x6110f000	         4	rw-S       	full          	server_memory
	39808	0x6910e000	0x6912e000	       128	rw-S       	full          	server_memory
	39736	0x71129000	0x7212a000	     16388	rw-s       	full          	Vision_15676_stack
	39900	0x72146000	0x7218b000	       276	rw-s       	full          	w>Vision_15688_stack
	39902	0x72190000	0x721d5000	       276	rw-s       	full          	l>will_code_for_food_15689_stac
	39886	0x721dd000	0x72222000	       276	rw-s       	full          	w>Setup window_15681_stack
	39810	0x72265000	0x722aa000	       276	rw-s       	full          	the_spirits_within_15679_stack
	39908	0x7258d000	0x725d2000	       276	rw-s       	full          	s>magic 8-nipple_15691_stack
	39906	0x726cb000	0x72710000	       276	rw-s       	full          	t>Kenichi_15690_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	1257705	    0	      15681	Setup window
	1257722	    0	       8489	TranslatorSettings Lock
	1259981	    0	        650	Catalog
	1260088	    0	       3549	PeriodicUpdatePoses
	1260122	    0	      15682	BLooperList lock
	1260148	    0	        650	TranslatorSettings Lock
	1260149	    0	        650	Catalog
	1260179	    0	      15691	token space
	1260180	    0	       1296	Catalog
	1260181	    0	      15676	AppServerLink_sLock
	1260184	    0	        650	LocaleRosterData
	1260186	    0	        650	some BLocker
	1260187	    0	        650	some BLocker
	1260188	    0	      12423	Catalog
	1260190	    0	          0	undo
	1260192	    0	      12424	Light Lock
	1260193	    0	          0	some BBlockCache lock
	1260194	    0	          0	synchronized hash map
	1260195	    0	       3555	Catalog
	1260196	    0	          0	some BLocker
	1260198	    0	       8643	some BLocker
	1260199	    0	          0	synchronized hash map
	1260200	    0	      13514	some BLocker
	1260202	    0	       1298	some BLocker
	1260204	    0	       3556	AppLooperPort
	1260205	    0	      13515	DNS cache
	1260207	    0	       3556	URLCrunch taglist
	1260210	    0	        533	Catalog
	1260213	    0	       8644	Light Lock
	1260217	    0	          0	some BLocker
	1260220	    0	      12426	clipboard
	1260221	    0	          0	some BLocker
	1260222	 1000	     -15688	active theme
	1260223	    0	          0	some BLocker
	1260224	    0	       8645	BMessageQueue Lock
	1260225	    0	          0	BMessageQueue Lock
	1260231	    0	          0	screen list
	1260234	    0	          0	width buffer
	1260236	    0	          0	Catalog
	1260237	    0	       1301	Catalog
	1260238	    0	          0	TranslatorSettings Lock
	1260239	    0	          0	TranslatorSettings Lock
	1260240	    0	       3559	TranslatorSettings Lock
	1260241	    0	      13519	Catalog
	1260242	    0	          0	Catalog
	1260246	    0	      13518	translator list
	1260250	    0	        533	TranslatorSettings Lock
	1260251	    0	        533	Catalog
	1260252	    0	          0	TranslatorSettings Lock
	1260253	    0	          0	Catalog
	1260256	    0	        533	TranslatorSettings Lock
	1260264	    0	          0	Catalog
	1260268	    0	          0	Catalog
	1260272	    0	          0	TranslatorSettings Lock
	1260275	    0	        533	PPM settings lock
	1260277	    0	          0	TranslatorSettings Lock
	1260278	    0	       1304	Catalog
	1260279	    0	          0	TranslatorSettings Lock
	1260280	    0	      12429	Catalog
	1260281	    0	          0	TranslatorSettings Lock
	1260282	    0	          0	Catalog
	1260284	    0	       8648	TranslatorSettings Lock
	1260285	    0	          0	TranslatorSettings Lock
	1260286	    0	          0	Catalog
	1260288	    0	          0	Catalog
	1260290	    0	      13523	Catalog
	1260291	    0	      13524	TranslatorSettings Lock
	1260294	    0	          0	TranslatorSettings Lock
	1260295	    0	       3563	Catalog
	1260296	    0	          0	TranslatorSettings Lock
	1260297	    0	      12430	TranslatorSettings Lock
	1260298	    0	       8649	Catalog
	1260310	    0	        533	tool tip manager
	1260321	    0	          0	Vision
	1260324	    0	          0	some BLocker
	1260326	    0	        533	BMessageQueue Lock
	1260336	    0	      12433	some BLocker
	1260337	   -1	      15690	VisionSendSync
	1260349	   -1	        533	logSynchLock_sem

</details>

**Comment by jscipione** [comment]
Probably related to Haiku bug #14624 https://dev.haiku-os.org/ticket/14264 which actually described a bug in Vision recently revealed by a change in Haiku involving one of the ListView subclasses (prob the one that ownes WindowListItem according crash report) used in Vision needs to call BListView::MouseDown() after doing its MouseDown() stuff.
