### ISSUE TITLE
Remove unimplemented Operator Window

### ISSUE THREAD

**Issue by janus2** [HaikuArchives/Vision#40]
If there are no objections I will remove the menu and the window.

![unimplemented window](https://user-images.githubusercontent.com/10423645/43364416-131cbd62-931a-11e8-850d-248ad01e3d31.png)

**Comment by scottmc** [comment]
Perhaps just comment it out for now, and open an enhancement ticket in case anyone feels the need to have this as a feature.

**Comment by KapiX** [comment]
If it's unimplemented there is no reason to leave it in. Remove it altogether, if there will be need to resurrect it, git history is here.
