### ISSUE TITLE
Add authentication support

### ISSUE THREAD

**Issue by KapiX** [HaikuArchives/Vision#41]
On FreeNode you can register your nickname. When you connect to the server you are asked to send a message to NickServ with your password to authenticate.
It would be nice if Vision could do that automatically when connecting.

Konversation has that feature.

**Comment by pulkomandy** [comment]
On Sat, Aug 04, 2018 at 12:32:12PM -0700, Kacper Kasper wrote:
> On FreeNode you can register your nickname. When you connect to the server you are asked to send a message to NickServ with your password to authenticate.
> It would be nice if Vision could do that automatically when connecting.

Most servers allow you to do this using the server password, which
Vision supports.

For example on Freenode:

https://freenode.net/kb/answer/registration

"If not, you can supply your login details, in the form
<account>:<password>, as a server password and they will be forwarded to
NickServ when you finish connecting. For example:

    /connect chat.freenode.net 6667 mquin:uwhY8wgzWw22-zXs.M39p

"

**Comment by scottmc** [comment]
Perhaps this tip can be added to Vision, under help or wherever it makes sense.

**Comment by KapiX** [comment]
Oh, ok, I found it. It's not what I'd call easily discoverable :/
