### ISSUE TITLE
Vision wont start "Missing symbol"

### ISSUE THREAD

**Issue by roired** [HaikuArchives/Vision#42]
![haiku_17_08_2018_17_26_45](https://user-images.githubusercontent.com/41487646/44274967-daabc980-a243-11e8-9e8a-cb58fea4fc73.png)
![virtualbox_haiku_17_08_2018_17_35_32](https://user-images.githubusercontent.com/41487646/44275037-0dee5880-a244-11e8-9c04-7bf4caee79f2.png)

Good day everyone,

Vision stopped working recently. On launch get a Dialog Window saying that:

Could not open "Vision" (Missing symbol: _ZN14BMessageFormatD1Ev)

And the only option available is to cancel. This has been happening since this wendnesday that I can recall, both on VBox and BMetal. Same nightly x64, and even a clean install of the latest nightly 52242.

Thanks for your support.
Regards,
RR

**Comment by pulkomandy** [comment]
This is already fixed on Vision side, and a recipe was sent to Haikuports. However the haikuports build bots are currently down for maintenance. The updated package will be available when the buildbots are back.

Nothing to fix on Vision side anymore, so closing the issue here.
