### ISSUE TITLE
Friulian translation ready

### ISSUE THREAD

**Issue by tmtfx** [HaikuArchives/Vision#55]
It's been a long time since I translated Vision to friulian language through https://i18n.kacperkasper.pl/projects , but I see it's still not merged.
So I filed this issue

Best regards

**Comment by waddlesplash** [comment]
I think Humdinger is going to export the translations to all relevant projects, and post new versions to HaikuPorts "soon", so they make it into the beta release.

**Comment by humdingerb** [comment]
Vision was updated with all new and updated languages. Thanks.
