### ISSUE TITLE
Use text "Vision" instead of an icon for the program menu

### ISSUE THREAD

**Issue by bitigchi** [HaikuArchives/Vision#58]
Having an icon for a menu label looks out of place. For consistency, program menu ought to use the program name, instead of anything else.

**Comment by waddlesplash** [comment]
There are a number of BeOS apps that use icons for the "app menu", so this is really not so unconventional.

**Comment by bitigchi** [comment]
I see. It might be a good idea to clearly state this in Haiku HIG, whether it's allowed or not then. I still think it's inconsistent though.

**Comment by pulkomandy** [comment]
The HIG says nothing, so it's allowed.
