### ISSUE TITLE
Vision crash while chosing font

### ISSUE THREAD

**Issue by Briseur** [HaikuArchives/Vision#66]
In preferences, You have a panel to chose fonts. It doesn't seem to save choices but it isn't the biggest problem.
Select the kind of message that you want to change, then scroll the font list down to select a font.
As the font list is a kind of preview by itself, it will crash. Note that I have a lot fonts installed (all from HD).
First time it crashed on Noto Sans Khmer, another time on Noto Sans arabic so it doesn't seem to be a specific font.
Unfortunately, the system completely hangs and it is impossible to launch the debugger;  the mouse is still moving but keyboard is not responding.

**Comment by pulkomandy** [comment]
If it crashes the whole system you probably want to report this on Haiku bugtracker instead: dev.haiku-os.org
No application should be able to do that and I suspect the problem is app_server being incompatible with some of the fonts you have installed.

**Comment by Briseur** [comment]
OK https://dev.haiku-os.org/ticket/17850

**Comment by lonemadmax** [comment]
Definitely an app_server problem, nothing to do on Vision's side.
