### ISSUE TITLE
 Bump version to 1.0

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Vision#8]
Since Vision is now using layout API we can bump it to 1.0 to celebrate it :)
Don't forget to update a recipe, upload new hpkg to HaikuPorts and update screenshots at HaikuDepot Server.

**Comment by KapiX** [comment]
It is not using layout API.
looncraz's PR only added live-updates support, he didn't rewrite Vision to use Layout Kit.

**Comment by diversys** [comment]
Indeed, my bad. Closing then.
